[project]
name = "data-visualization-for-food-scientists"
version = "0.1.0"
description = "Jupyter Book for teaching data visualization to Food Scientists"
authors = [
    { name = "Michal Ziemski", email = "mziemski@ethz.ch" },
    { name = "Doriela Grabocka", email = "dgrabocka@student.ethz.ch" },
    { name = "Nicholas Bokulich", email = "nicholas.bokulich@hest.ethz.ch" },
]
readme = "README.md"
requires-python = ">=3.10,<3.11"
dependencies = [
    "jupyter-book>=1.0.3,<2",
    "matplotlib==3.7.1",
    "numpy>=1.24.1,<2",
    "pandas<2",
    "plotly==5.9.0",
    "seaborn>=0.13.2,<0.14",
    "umap-learn>=0.5.9,<0.6",
    "numba>=0.61,<0.62",
]

[dependency-groups]
dev = ["jupyterlab>=4.5.7,<5"]

[tool.uv]
package = false
